name: flutter_core
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_screenutil: ^0.6.1
  auto_size_text: ^2.1.0
  provider: ^4.1.2
  flutter_svg: ^0.15.0
  sqflite: any
  flutter_datetime_picker: ^1.3.8
  carousel_slider: ^1.4.1
  http: ^0.12.0+2
  flutter_facebook_login: ^3.0.0
  validators: ^2.0.0
  firebase_database: ^3.1.6
  cloud_firestore: ^0.13.6
  firebase_storage: ^3.1.6
  shared_preferences: ^0.5.6
  mailer: ^3.0.4
  image_cropper: ^1.2.1
  image_picker: ^0.6.7
  google_sign_in: ^4.5.1
  firebase_auth: ^0.16.1
  #bottom_navy_bar: ^5.4.0
  pull_to_refresh: ^1.5.7
  material_design_icons_flutter: ^4.0.5345
  page_view_indicators: ^1.3.1
  crypto: ^2.1.4
  animated_text_kit: ^2.2.0
  cached_network_image: ^2.2.0+1
  photo_view: ^0.9.2
  firebase_messaging: ^6.0.16
  flutter_local_notifications: ^1.4.4
  fluttertoast: ^4.0.1
  file_picker: ^1.10.0
  numberpicker: ^1.2.0
  double_back_to_close_app: ^1.2.0
  flutter_money_formatter:
    git:
      url: git://github.com/anisalibegic/flutter_money_formatter.git
  map_launcher: ^0.5.0
  flutter_xlider: ^3.4.0
  flutter_switch: ^0.1.0
  connectivity: ^0.4.9
  geolocator:
    git:
        url: https://github.com/Baseflow/flutter-geolocator.git
  location: ^3.0.2
  # The following adds the HERE SDK for Flutter plugin folder to your application.
  here_sdk:
    path: plugins/here_sdk
  path_provider: ^1.6.11
  exif: ^1.0.3
  geoflutterfire: ^2.1.0
  network_image_to_byte: ^0.0.1
  flutter_image_compress: ^0.7.0
  flutter_speed_dial: ^1.2.5
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/
  - assets/database/

  fonts:
   - family: OpenSans
     fonts:
       - asset: assets/fonts/OpenSans-Light.ttf
         weight: 300
       - asset: assets/fonts/OpenSans-LightItalic.ttf
         weight: 300
         style: italic
       - asset: assets/fonts/OpenSans-Regular.ttf
         weight: 400
       - asset: assets/fonts/OpenSans-Italic.ttf
         weight: 400
         style: italic
       - asset: assets/fonts/OpenSans-SemiBold.ttf
         weight: 600
       - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
         weight: 600
         style: italic
       - asset: assets/fonts/OpenSans-Bold.ttf
         weight: 700
       - asset: assets/fonts/OpenSans-BoldItalic.ttf
         weight: 700
         style: italic
       - asset: assets/fonts/OpenSans-ExtraBold.ttf
         weight: 800
       - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
         weight: 800
         style: italic
